### ISSUE TITLE
Create a logo for webevaluator

### ISSUE THREAD

**Issue by Aman-Codes** [webevaluator/webevaluator.github.io#9]
# Description
We need to create a logo for webevaluator. The best design suggested would be used for the website.

# Note
- The logo must be the original work of the contributor. They are not allowed to use any online image or any tool which will restrict us to use the image due to copyright, license or trademark issue.
- You are free to use any platform of your choice for logo creation like Figma, Adobe Xd etc.

**Comment by mishrapratiksha26** [comment]
I am interested in suggesting some designs may I work on this?

**Comment by Aman-Codes** [comment]
Sure @mishrapratiksha26 go ahead

**Comment by mishrapratiksha26** [comment]
here's a logo i created on canva pls let me know if any changes are required

![Web Evaluator (2)](https://user-images.githubusercontent.com/102692034/205690945-7b6fdb6e-ba6e-4c7b-85d9-025daa2c57e1.png)

**Comment by mishrapratiksha26** [comment]
here's a logo i created in canva pls let me know if any changes are required

https://www.canva.com/design/DAFT4y-voxY/afhAC1hTgiF0IuJ3ICiwyA/edit?utm_content=DAFT4y-voxY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by mishrapratiksha26** [comment]
Here's a logo i designed using canva pls let me know if any changes are required 
https://www.canva.com/design/DAFT4y-voxY/afhAC1hTgiF0IuJ3ICiwyA/edit?utm_content=DAFT4y-voxY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Aman-Codes** [comment]
Hi @mishrapratiksha26 thank you for your contribution. Our team loved your design and have approved it 🥳. Could you please make a pull request to replace the file `logo192.png` and `logo512.png` (inside public folder) with your design.

**Comment by mishrapratiksha26** [comment]
Sure!! Doing that now...
